### ISSUE TITLE
`body` not available in custom loader on POST endpoint

### ISSUE THREAD

**Issue by michaelcamper** [namics/request-registry#5]
When using a custom loader for a POST endpoint, `body` is not available in the `loader` interface and can not be passed to the custom loader implementation

```
export const carwayUpdateOfferEndpoint = createPostEndpoint<
  { offerID: string },
  { markAsAccepted?: boolean; markAsSeen?: boolean }
>({
  url: ({ offerID }) => `/carway/offers?offerId=${offerID}`,
  loader: (keys, url) => apiClient.post(url) // body not available
});
```

**Comment by jantimon** [comment]
Oh sorry to hear - I’ll have to take a look into that

**Comment by jantimon** [comment]
Unfortunately that is not possible because of the caching strategy
